#!/usr/bin/env ruby
# This file simply includes the encryption/decryption code, then calls the
# "encrypt" method on the text that's sent in.

require_relative 'encrypt.rb'
puts encrypt(ARGV.join(" "))
